title: Francisco Costa – Portfolio
description: Finance • Excel • Python
markdown: kramdown

nav_links:
  - name: Home
    url: /
  - name: Online CV
    url: /cv
  - name: Excel
    url: /excel
  - name: Python
    url: /python
