title: Francisco Costa
description: Portfolio – Excel & Python
markdown: kramdown

nav_links:
  - name: Home
    url: /
  - name: Online CV
    url: /cv
  - name: Excel
    url: /excel
  - name: Python
    url: /python
sass:
  style: compressed

# Minima override
minima:
  skin: custom
  include_css:
    - assets/css/custom.css

