title: Francisco Costa – Portfolio
description: Finance • Excel • Python
theme: minima  # We’ll override with custom layout
markdown: kramdown

# Navigation links
nav_links:
  Home: /
  Online CV: /cv
  Excel: /excel
  Python: /python
